"use client";

import Link from "next/link";
import { ArrowLeft, FileText } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#050505] text-[#ededed] overflow-hidden flex flex-col">
      <nav className="flex items-center justify-between px-8 py-6 max-w-7xl w-full mx-auto border-b border-white/5">
        <Link href="/" className="text-xl font-bold tracking-tight hover:opacity-80 transition-opacity">
          Promptify <span className="text-white/70">AI</span>
        </Link>
        <Link href="/" className="flex items-center gap-2 text-sm font-medium text-white/60 hover:text-white transition-colors">
          <ArrowLeft className="w-4 h-4" /> Back to Home
        </Link>
      </nav>

      <main className="flex-1 max-w-4xl w-full mx-auto px-8 py-16 flex flex-col">
        <div className="flex items-center gap-4 mb-8">
          <FileText className="w-8 h-8 text-red-500" />
          <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight">Terms of Service</h1>
        </div>
        
        <div className="prose prose-invert prose-red max-w-none text-white/70">
          <p className="text-lg mb-8">Last updated: May 2026</p>
          
          <h2 className="text-2xl font-bold text-white mt-10 mb-4">1. Acceptance of Terms</h2>
          <p className="mb-6">
            By accessing and using Promptify AI, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by these terms, please do not use our service.
          </p>
          
          <h2 className="text-2xl font-bold text-white mt-10 mb-4">2. Use of Service</h2>
          <p className="mb-6">
            Our prompt enhancement engine is provided &quot;as is&quot;. We are not responsible for the downstream outputs generated by third-party LLMs using prompts created by our tool. Users are responsible for ensuring their prompts do not violate the safety guidelines of their respective AI providers.
          </p>

          <h2 className="text-2xl font-bold text-white mt-10 mb-4">3. Intellectual Property</h2>
          <p className="mb-6">
            The structure, algorithms, and design of the Promptify Engine are the intellectual property of Promptify AI. The specific prompt texts generated for you are your property to use commercially or personally.
          </p>
        </div>
      </main>
    </div>
  );
}
